name: untitled14
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk:


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:


  uses-material-design: true

  assets:
     - assets/images/





